### ISSUE TITLE
Compatibility with PSR-16/PSR-6

### ISSUE THREAD

**Issue by eweso** [laminas/laminas-cache-storage-adapter-filesystem#7]
#### Summary

PSR-16 allows "A-Z, a-z, 0-9, _, and ." as valid key characters for the cache item name. But the key name pattern of the Filesystem storage is "/^[a-z0-9_\+\-]*$/Di" and therefore doesn't match PSR-16 since "." isn't allowed here. This leads to errors when using the simple cache decorator on libraries such as "browscap/browscap-php" that has a cache item named "browscap.version".

#### Current behavior

Using the simple cache decorator with a laminas cache storage such as Filesystem throws an Exception when a dot is used inside the cache item name.

#### Expected behavior

The cache storage should accept key names with a dot since it's specified by PSR-16 and breaks standard compatibility with the simple cache decorator. A valid key pattern for the Filesystem storage could be this one "^[a-z0-9_\+\-\.]*$/Di".

**Comment by boesing** [comment]
Filesystem Storage does not fully support PSR-16. 

https://github.com/laminas/laminas-cache-storage-adapter-filesystem/blob/aa56c2ee326aa1b4b44d2e9ee6dbc35976990e01/test/integration/Psr/SimpleCache/FilesystemIntegrationTest.php#L51-L54

The problem is, that you cannot specify dynamic TTL per cache key and thus, you have exactly one possible TTL which is not useful when you are using the `PSR-16`.

So I would not recommend using Filesystem in combination with `PSR-6` or `PSR-16`.
Filesystem cache items are not being "deleted" when they expire as they do not hold their own TTL.
That could be an improvement but its not implemented like this for now.

Feel free to provide a PR with proper implementation. I am happy to merge this for the next major as it would be a BC break anyways.

I've implemented this in some of my projects like this:
- Write another file which contains the TTL
- On read, read the TTL file first and then verify the filemtime of the file containing the cached data
- delete the file if TTL exceeded

But this will require pretty much I/O so today, I would probably change the internal cache file format to pass the `TTL` with the cached data. So in case `filemtime` did not exceed `TTL`, returning the cached data would be fine. If its exceeded, treat it as the cache isnt available and delete the file accordingly.

---
So, regarding this, I would change the Issue type from `Bug` to `Feature Request` as the `Filesystem` adapter never stated that it is compatible with PSR-16.

**Comment by montypanday** [comment]
Hi team,

I encountered the same issue with using PhpSpreadsheet.

The key 'phpspreadsheet.65e162e5970b33.58521221.A1' doesn't match against pattern '/^[a-z0-9_\+\-]*$/Di'

Using Laminas filesystem cache adapter with the SimpleCacheDecorator

Kind regards

**Comment by boesing** [comment]
> The key 'phpspreadsheet.65e162e5970b33.58521221.A1' doesn't match against pattern '/^[a-z0-9_\+\-]*$/Di'
> 

That is due to the default key pattern. You can change that and allow `.` by passing the appropriate option. 
The cache decorator just receives a configured Adapter, so it would also fail without simple cache and thus not a PSR-16 issue but configuration issue.

But we can adapt key pattern in the future to allow dots. I do not see a big deal with that. 

Would you mind creating an RFC in a new issue? I do not have a need for this and thus having first hand infos such as your library ur using, etc. would provide a good base to discuss widening the key pattern. 

Thanks in advance.

**Comment by boesing** [comment]
FYI: 

With the next major version, the `Filesystem` adapter will have TTL per-item functionality and thus, both PSR-6 and PSR-16 are supported.
